apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: mysql
spec:
  serviceName: mysql-service
  replicas: 3
  selector:
    matchLabels:  # ✅ FIXED: was matchlabels
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0  # ✅ FIXED: "mtsql" likely a typo unless it's custom
          ports:
            - containerPort: 3306  # ✅ FIXED: was containersPort
          env:
            - name: MYSQL_ROOT_PASSWORD  # ✅ FIXED: was MYSQL_ROOT_PASWORD
              value: root
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_DATABASE 
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata: 
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
