kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager    #role ka name
  namespace: apache
rules:
  - apiGroups: ["*"]
    resources: ["deployment","pod","service"]
    verbs: ["get","apply","delete","create","watch","patch"]
