kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: apache-vpa
  namespace: apache
spec:
  targetRef:
    name: apache-deployment
    apiversion: apps/v1
    kind: deployment

  updatePolicy:
    updateMode: "Auto"
